# Generated by Django 3.2.6 on 2021-08-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cafeName', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('city', models.CharField(blank=True, choices=[('서울-강남', '서울-강남'), ('서울-강북', '서울-강븍')], max_length=10, null=True, verbose_name='시')),
                ('country', models.CharField(blank=True, choices=[('마포', '마포'), ('공덕', '공덕'), ('홍대', '홍대'), ('합정', '합정'), ('상수', '상수')], max_length=10, null=True, verbose_name='구')),
                ('district', models.CharField(blank=True, choices=[('test', 'test')], max_length=10, null=True, verbose_name='동')),
                ('address', models.CharField(max_length=150)),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('instant_book', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
