# Generated by Django 3.2.6 on 2021-08-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_cafe_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('coffeeMenu', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cafe',
            name='coffee_menu',
            field=models.ManyToManyField(blank=True, to='cafes.CoffeeMenu'),
        ),
    ]
