# Generated by Django 3.2.6 on 2021-08-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_auto_20210819_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CafeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='coffee_menu',
        ),
        migrations.DeleteModel(
            name='CoffeeMenu',
        ),
        migrations.AddField(
            model_name='cafe',
            name='amenities',
            field=models.ManyToManyField(to='cafes.Amenity'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='coffee_type',
            field=models.ManyToManyField(blank=True, to='cafes.CafeType', verbose_name='커피 메뉴'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='facilities',
            field=models.ManyToManyField(to='cafes.Facility'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='house_rules',
            field=models.ManyToManyField(to='cafes.HouseRule'),
        ),
    ]
