# Generated by Django 3.2.6 on 2021-08-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0005_auto_20210819_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='cafeNumber',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='coffee_type',
        ),
        migrations.AddField(
            model_name='cafe',
            name='cafetype',
            field=models.ManyToManyField(blank=True, to='cafes.CafeType', verbose_name='커피 메뉴'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='facilities',
            field=models.ManyToManyField(blank=True, null=True, to='cafes.Facility'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='house_rules',
            field=models.ManyToManyField(blank=True, null=True, to='cafes.HouseRule'),
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.AddField(
            model_name='cafe',
            name='cafeMenu',
            field=models.ManyToManyField(blank=True, null=True, to='cafes.Menu'),
        ),
    ]
