# Generated by Django 3.2.6 on 2021-08-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0006_auto_20210819_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='메뉴'),
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='가격'),
        ),
    ]
