# Generated by Django 3.2.6 on 2021-08-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0007_auto_20210819_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='check_out',
        ),
        migrations.AddField(
            model_name='cafe',
            name='end',
            field=models.TimeField(blank=True, null=True, verbose_name='영업 종료시간'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='영업 시작시간'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='가격'),
        ),
    ]
