# Generated by Django 3.2.6 on 2021-08-19 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0008_auto_20210819_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=80)),
                ('file', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cafetype',
            options={'verbose_name_plural': '카페 종류'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': '메뉴'},
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='house_rules',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='instant_book',
        ),
        migrations.AddField(
            model_name='cafe',
            name='parkSite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='HouseRule',
        ),
        migrations.AddField(
            model_name='photo',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.cafe'),
        ),
    ]
