# Generated by Django 3.2.6 on 2021-08-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0009_auto_20210819_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='cafeMenu',
            field=models.ManyToManyField(blank=True, to='cafes.Menu'),
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='cafetype',
        ),
        migrations.AddField(
            model_name='cafe',
            name='cafetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafes.cafetype', verbose_name='커피 메뉴'),
        ),
    ]
