# Generated by Django 3.2.6 on 2021-08-22 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0011_alter_cafe_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='cafe',
            name='cafeMenu',
            field=models.ManyToManyField(blank=True, related_name='owner', to='cafes.Menu'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='cafetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='cafes.cafetype', verbose_name='커피 메뉴'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafephotos', to='cafes.cafe'),
        ),
    ]
