# Generated by Django 3.2.6 on 2021-08-22 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0012_auto_20210822_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='cafetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='cafes.cafetype', verbose_name='카페 타입'),
        ),
    ]
