# Generated by Django 3.2.6 on 2021-08-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0013_alter_cafe_cafetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='cafeImages'),
        ),
    ]
