# Generated by Django 3.2.6 on 2021-10-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0014_alter_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='city',
            field=models.CharField(blank=True, choices=[('서울-강남', '서울-강남'), ('서울-강북', '서울-강븍'), ('제주', '제주'), ('부산', '부산'), ('경기', '경기')], max_length=10, null=True, verbose_name='시'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='country',
            field=models.CharField(blank=True, choices=[('마포', '마포'), ('공덕', '공덕'), ('홍대', '홍대'), ('합정', '합정'), ('상수', '상수'), ('강남', '강남'), ('논현', '논현'), ('신사', '신사')], max_length=10, null=True, verbose_name='구'),
        ),
    ]
