# Generated by Django 3.2.6 on 2021-10-11 14:17

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0020_auto_20211011_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newcontinent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafeCity', to='cafes.city')),
                ('newcountry', smart_selects.db_fields.ChainedForeignKey(chained_field='newcontinent', chained_model_field='continent', on_delete=django.db.models.deletion.CASCADE, to='cafes.country')),
            ],
        ),
    ]
