# Generated by Django 3.2.6 on 2021-10-11 15:02

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0022_auto_20211011_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='newcontinent',
            new_name='choiceCity',
        ),
        migrations.AlterField(
            model_name='cafe',
            name='newcountry',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='newcontinent', chained_model_field='choiceCity', null=True, on_delete=django.db.models.deletion.CASCADE, to='cafes.country'),
        ),
    ]
