# Generated by Django 3.2.6 on 2021-08-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cleanPoint',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
