# Generated by Django 3.2.6 on 2021-08-22 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0013_alter_cafe_cafetype'),
        ('reviews', '0002_alter_review_cleanpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cafes.cafe'),
        ),
    ]
